site_name: AC/CA
site_url: https://accapwr.org/docs

theme:
  name: material
  palette: 
    - scheme: slate
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    - scheme: default
      toggle:
        icon: material/brightness-4
        name: Switch to light mode